#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

/// <summary>
/// Creates editor-side assets for Phase 1: tags, layers, material assets, and a starter scene.
/// The runtime scene is still generated by GameManager and SceneBuilder.
/// </summary>
[InitializeOnLoad]
public static class Phase1ProjectSetup
{
    private const string ScenePath = "Assets/Scenes/Phase1RoadSegmentation.unity";

    private static readonly string[] TagsAndLayers =
    {
        "Road_Normal",
        "Road_Puddle",
        "Road_Crack",
        "Road_Bump",
        "Road_Hole",
        "Road_Construction",
        "Road_Obstacle",
        "Sidewalk",
        "LaneLine",
        "Crosswalk",
        "Building",
        "TrafficLight",
        "PedestrianArea",
        "Background"
    };

    private static readonly Dictionary<string, Color> NormalColors = new Dictionary<string, Color>
    {
        {"normal_road", new Color(0.20f, 0.20f, 0.19f)},
        {"sidewalk", new Color(0.60f, 0.58f, 0.52f)},
        {"lane_line", new Color(0.92f, 0.90f, 0.84f)},
        {"crosswalk", new Color(0.92f, 0.90f, 0.84f)},
        {"puddle", new Color(0.06f, 0.18f, 0.28f, 0.85f)},
        {"crack", new Color(0.02f, 0.02f, 0.02f)},
        {"bump", new Color(0.33f, 0.28f, 0.21f)},
        {"hole", new Color(0.01f, 0.01f, 0.01f)},
        {"construction_area", new Color(0.95f, 0.45f, 0.05f)},
        {"obstacle", new Color(0.45f, 0.25f, 0.12f)},
        {"building", new Color(0.52f, 0.55f, 0.57f)},
        {"traffic_light", new Color(0.05f, 0.05f, 0.05f)},
        {"pedestrian_area", new Color(0.36f, 0.40f, 0.31f)},
        {"background", new Color(0.38f, 0.44f, 0.34f)}
    };

    private static readonly Dictionary<string, Color> SegmentationColors = new Dictionary<string, Color>
    {
        {"normal_road", new Color(0.2f, 0.2f, 0.2f)},
        {"sidewalk", new Color(0.55f, 0.35f, 0.1f)},
        {"lane_line", Color.yellow},
        {"crosswalk", new Color(1f, 0f, 1f)},
        {"puddle", new Color(0f, 0.4f, 1f)},
        {"crack", Color.black},
        {"bump", new Color(1f, 0.5f, 0f)},
        {"hole", new Color(0.45f, 0f, 0f)},
        {"construction_area", Color.red},
        {"obstacle", Color.cyan},
        {"building", new Color(0.35f, 0.1f, 0.7f)},
        {"traffic_light", new Color(1f, 0.85f, 0f)},
        {"pedestrian_area", Color.green},
        {"background", new Color(0.1f, 0.1f, 0.1f)}
    };

    static Phase1ProjectSetup()
    {
        EditorApplication.delayCall += EnsureProjectAssets;
    }

    [MenuItem("Tools/Road Segmentation/Setup Phase 1 Scene")]
    public static void EnsureProjectAssets()
    {
        EnsureFolders();
        EnsureTagsAndLayers();
        EnsureMaterials();
        EnsureScene();
        AssetDatabase.SaveAssets();
    }

    private static void EnsureFolders()
    {
        EnsureFolder("Assets", "Scripts");
        EnsureFolder("Assets/Scripts", "Runtime");
        EnsureFolder("Assets/Scripts", "Editor");
        EnsureFolder("Assets", "Materials");
        EnsureFolder("Assets", "Scenes");
        EnsureFolder("Assets", "Docs");
    }

    private static void EnsureFolder(string parent, string child)
    {
        string path = parent + "/" + child;
        if (!AssetDatabase.IsValidFolder(path))
        {
            AssetDatabase.CreateFolder(parent, child);
        }
    }

    private static void EnsureTagsAndLayers()
    {
        SerializedObject tagManager = new SerializedObject(AssetDatabase.LoadAllAssetsAtPath("ProjectSettings/TagManager.asset")[0]);
        SerializedProperty tags = tagManager.FindProperty("tags");

        foreach (string tagName in TagsAndLayers)
        {
            if (!TagExists(tags, tagName))
            {
                tags.InsertArrayElementAtIndex(tags.arraySize);
                tags.GetArrayElementAtIndex(tags.arraySize - 1).stringValue = tagName;
            }
        }

        SerializedProperty layers = tagManager.FindProperty("layers");
        foreach (string layerName in TagsAndLayers)
        {
            if (!LayerExists(layers, layerName))
            {
                AddLayer(layers, layerName);
            }
        }

        tagManager.ApplyModifiedProperties();
    }

    private static bool TagExists(SerializedProperty tags, string tagName)
    {
        for (int i = 0; i < tags.arraySize; i++)
        {
            if (tags.GetArrayElementAtIndex(i).stringValue == tagName)
            {
                return true;
            }
        }

        return false;
    }

    private static bool LayerExists(SerializedProperty layers, string layerName)
    {
        for (int i = 0; i < layers.arraySize; i++)
        {
            if (layers.GetArrayElementAtIndex(i).stringValue == layerName)
            {
                return true;
            }
        }

        return false;
    }

    private static void AddLayer(SerializedProperty layers, string layerName)
    {
        for (int i = 8; i < layers.arraySize; i++)
        {
            SerializedProperty layer = layers.GetArrayElementAtIndex(i);
            if (string.IsNullOrEmpty(layer.stringValue))
            {
                layer.stringValue = layerName;
                return;
            }
        }

        Debug.LogWarning("No empty Unity layer slot remains for " + layerName + ". Runtime will use Default layer for it.");
    }

    private static void EnsureMaterials()
    {
        foreach (KeyValuePair<string, Color> pair in NormalColors)
        {
            CreateMaterialAsset("Assets/Materials/MAT_Normal_" + pair.Key + ".mat", pair.Value);
        }

        foreach (KeyValuePair<string, Color> pair in SegmentationColors)
        {
            CreateMaterialAsset("Assets/Materials/MAT_Seg_" + pair.Key + ".mat", pair.Value);
        }
    }

    private static void CreateMaterialAsset(string path, Color color)
    {
        if (File.Exists(path))
        {
            Material existing = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (existing != null)
            {
                existing.color = color;
                existing.SetFloat("_Glossiness", 0.22f);
                EditorUtility.SetDirty(existing);
            }
            return;
        }

        Material material = new Material(Shader.Find("Standard"))
        {
            color = color
        };
        material.SetFloat("_Glossiness", 0.22f);
        AssetDatabase.CreateAsset(material, path);
    }

    private static void EnsureScene()
    {
        if (File.Exists(ScenePath))
        {
            return;
        }

        Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
        scene.name = "Phase1RoadSegmentation";

        GameObject managers = new GameObject("Managers");
        GameObject gameManager = new GameObject("GameManager");
        gameManager.transform.SetParent(managers.transform, false);
        gameManager.AddComponent<GameManager>();

        EditorSceneManager.SaveScene(scene, ScenePath);
        Debug.Log("Created " + ScenePath + ". Open it and press Play to generate the Phase 1 scene.");
    }
}
#endif
